//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gästebuch.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GästebuchEntities1 : DbContext
    {
        public GästebuchEntities1()
            : base("name=GästebuchEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Admin> tbl_Admin { get; set; }
        public virtual DbSet<tbl_Eintrag> tbl_Eintrag { get; set; }
        public virtual DbSet<tbl_Log> tbl_Log { get; set; }
    
        public virtual int usp_EinträgeAutorisieren(string eintragID, Nullable<System.Guid> adminID)
        {
            var eintragIDParameter = eintragID != null ?
                new ObjectParameter("EintragID", eintragID) :
                new ObjectParameter("EintragID", typeof(string));
    
            var adminIDParameter = adminID.HasValue ?
                new ObjectParameter("AdminID", adminID) :
                new ObjectParameter("AdminID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EinträgeAutorisieren", eintragIDParameter, adminIDParameter);
        }
    
        public virtual int usp_EinträgeLöschen(string ipAdresse, string eintragID)
        {
            var ipAdresseParameter = ipAdresse != null ?
                new ObjectParameter("IpAdresse", ipAdresse) :
                new ObjectParameter("IpAdresse", typeof(string));
    
            var eintragIDParameter = eintragID != null ?
                new ObjectParameter("EintragID", eintragID) :
                new ObjectParameter("EintragID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EinträgeLöschen", ipAdresseParameter, eintragIDParameter);
        }
    }
}
