//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gästebuch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Log
    {
        public System.Guid ID { get; set; }
        public string IP_Adresse { get; set; }
        public string Vorgang { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
    }
}
