//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gästebuch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Eintrag
    {
        public System.Guid ID { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public string Detailtext { get; set; }
        public string Verbesserungen { get; set; }
        public Nullable<byte> Bewertung { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<System.Guid> autorisiert_von { get; set; }
    
        public virtual tbl_Admin tbl_Admin { get; set; }
    }
}
